FROM ubuntu:14.04

ENV LANG C.UTF-8

RUN  apt-get update \
  && apt-get -y install software-properties-common \
  && add-apt-repository ppa:deadsnakes/ppa \
  && apt-get update \
  && apt-get install -y apt-utils \
  && apt-get install -y wget \
  && apt-get install -y git \
  && apt-get install -y python3.6 \
  && apt-get install -y python3.6-dev \
  && apt-get install -y libjudy-dev \
  && apt-get install -y rsync \
  && apt-get install -y gawk \
  && apt-get install -y g++ \
  && apt-get install -y build-essential \
  && rm -rf /var/lib/apt/lists/*

RUN git clone --branch progress-logging --single-branch https://github.com/TeMU-BSC/corpus-cleaner.git

RUN mkdir /cc

RUN mv /corpus-cleaner /cc

RUN rm -rf /cc/corpus-cleaner/data/

RUN rm -rf /cc/corpus-cleaner/output/

RUN wget https://bootstrap.pypa.io/get-pip.py \
  && python3.6 get-pip.py

RUN python3.6 -m pip install -r /cc/corpus-cleaner/requirements.txt

RUN bash /cc/corpus-cleaner/get-third-party-docker.sh

ENTRYPOINT ["bash", "/cc/corpus-cleaner/entrypoint.sh"]
